dist: xenial
language: c

matrix:
  include:
    - compiler: gcc
      env:
        - TARGET=distcheck
      addons:
        apt:
          packages:
            - libcmocka-dev
    - compiler: clang
      env:
        - TARGET=distcheck
        - DISABLE_PUBLISHER=1
      addons:
        apt:
          packages:
            - libcmocka-dev
    - os: osx
      osx_image: xcode11
      compiler: clang
      env:
        - TARGET=distcheck
        - DISABLE_PUBLISHER=1
      addons:
        homebrew:
          packages:
            - cmocka
            - xz
    - compiler: gcc
      env:
        - TARGET=valgrind
      addons:
        apt:
          packages:
            - libcmocka-dev
            - valgrind
    - compiler: clang
      env:
        - TARGET=valgrind
      addons:
        apt:
          packages:
            - libcmocka-dev
            - valgrind
    - compiler: clang
      env:
        - TARGET=clang-analyzer
    - compiler: gcc
      env:
        - TARGET=dist-docs
      addons:
        apt:
          packages:
            - doxygen
    - compiler: gcc
      env:
        - TARGET=dist-srpm
      addons:
        apt:
          packages:
            - rpm

install:
  - gem install ronn

script: curl -sSf https://yatr.rgm.io/run.sh | bash
